param(
    [string]$Python64Exe = ".\.venv38\Scripts\python.exe",
    [string]$Python32Exe = ".\.venv38_x86\Scripts\python.exe",
    [switch]$SkipDepsInstall,
    [switch]$SkipInstaller,
    [string]$InnoSetupCompiler,
    [string]$Version
)

$ErrorActionPreference = "Stop"

function Resolve-ProjectPath([string]$Root, [string]$PathValue) {
    if ([string]::IsNullOrWhiteSpace($PathValue)) {
        return $null
    }
    if ([System.IO.Path]::IsPathRooted($PathValue)) {
        return [System.IO.Path]::GetFullPath($PathValue)
    }
    return [System.IO.Path]::GetFullPath((Join-Path $Root $PathValue))
}

function Require-File([string]$PathValue, [string]$Hint, [string]$Suggestion = "") {
    if (-not $PathValue -or -not (Test-Path -LiteralPath $PathValue)) {
        $msg = "$Hint not found: $PathValue"
        if (-not [string]::IsNullOrWhiteSpace($Suggestion)) {
            $msg += "`n$Suggestion"
        }
        throw $msg
    }
}

function Get-PythonMeta([string]$PythonExePath) {
    $jsonText = & $PythonExePath -c "import json,struct,sys; print(json.dumps({'version':'.'.join(map(str, sys.version_info[:3])), 'major':sys.version_info[0], 'minor':sys.version_info[1], 'bits':struct.calcsize('P')*8}))"
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to inspect Python runtime: $PythonExePath"
    }
    try {
        return ($jsonText | ConvertFrom-Json)
    } catch {
        throw "Failed to parse Python metadata from: $PythonExePath"
    }
}

function Assert-Win7PythonMeta($Meta, [string]$ArchLabel, [string]$PythonExePath) {
    $versionText = [string]$Meta.version
    $major = [int]$Meta.major
    $minor = [int]$Meta.minor
    $bits = [int]$Meta.bits

    if ($major -ne 3 -or $minor -ne 8) {
        throw "$ArchLabel build requires Python 3.8.x, but got $versionText at: $PythonExePath"
    }

    $expectedBits = if ($ArchLabel -eq "x86") { 32 } else { 64 }
    if ($bits -ne $expectedBits) {
        throw "$ArchLabel build requires ${expectedBits}-bit Python, but got ${bits}-bit at: $PythonExePath"
    }
}

function Invoke-Win7Build(
    [string]$ProjectRoot,
    [string]$BuildScript,
    [string]$ArchLabel,
    [string]$PythonExePath,
    [bool]$SkipDepsInstallFlag,
    [string]$OutputDir
) {
    Write-Host "=== Building $ArchLabel Win7 package ===" -ForegroundColor Cyan
    Require-File $PythonExePath "Python executable"

    $buildParams = @{
        Win7Compatible = $true
        PythonExe = $PythonExePath
    }
    if ($SkipDepsInstallFlag) {
        $buildParams.SkipDepsInstall = $true
    }

    & $BuildScript @buildParams
    if ($LASTEXITCODE -ne 0) {
        throw "build_exe.ps1 failed for $ArchLabel (exit code: $LASTEXITCODE)"
    }

    $builtExe = Join-Path $ProjectRoot "dist\vehicle_screening.exe"
    Require-File $builtExe "Built executable"

    $targetExe = Join-Path $OutputDir "vehicle_screening_win7_$ArchLabel.exe"
    Copy-Item -LiteralPath $builtExe -Destination $targetExe -Force

    $hash = (Get-FileHash -LiteralPath $targetExe -Algorithm SHA256).Hash.ToLowerInvariant()
    Write-Host "Saved: $targetExe" -ForegroundColor Green
    Write-Host "SHA256: $hash"

    return @{
        Arch = $ArchLabel
        ExePath = $targetExe
        Sha256 = $hash
    }
}

function Resolve-Iscc([string]$PreferredPath) {
    $candidates = @()
    if ($PreferredPath) {
        $candidates += $PreferredPath
    }

    $pathCommand = Get-Command "ISCC.exe" -ErrorAction SilentlyContinue
    if ($pathCommand) {
        $candidates += $pathCommand.Source
    }

    $candidates += "$env:ProgramFiles(x86)\Inno Setup 6\ISCC.exe"
    $candidates += "$env:ProgramFiles\Inno Setup 6\ISCC.exe"

    foreach ($item in $candidates) {
        if ([string]::IsNullOrWhiteSpace($item)) { continue }
        if (Test-Path -LiteralPath $item) {
            return [System.IO.Path]::GetFullPath($item)
        }
    }
    return $null
}

function Write-Sha256Sums([string]$HashFile, [object[]]$Items) {
    $hashLines = @()
    foreach ($item in $Items) {
        $hashLines += "$($item.Sha256) *$(Split-Path -Leaf $item.Path)"
    }
    [System.IO.File]::WriteAllLines($HashFile, $hashLines, [System.Text.Encoding]::UTF8)
}

function New-InnoScript(
    [string]$ScriptPath,
    [string]$ArchLabel,
    [string]$VersionText,
    [string]$SourceExePath,
    [string]$OutputDir,
    [string]$OutputBase
) {
    $archAllowed = if ($ArchLabel -eq "x64") { "x64" } else { "x86 x64" }
    $appId = if ($ArchLabel -eq "x64") {
        "{E2B1FD4B-97E7-4D3E-A1D5-8A4C8D850641}"
    } else {
        "{E2B1FD4B-97E7-4D3E-A1D5-8A4C8D850642}"
    }
    $archInstallLine = if ($ArchLabel -eq "x64") { "ArchitecturesInstallIn64BitMode=x64" } else { $null }

    $rawLines = @(
        "; Auto-generated by build_win7_dual_installers.ps1",
        "[Setup]",
        "AppId=$appId",
        "AppName=Vehicle Screening",
        "AppVersion=$VersionText",
        "AppPublisher=Local Build",
        "DefaultDirName={autopf}\VehicleScreening",
        "DefaultGroupName=Vehicle Screening",
        "DisableProgramGroupPage=yes",
        "Compression=lzma2",
        "SolidCompression=yes",
        "WizardStyle=modern",
        "ArchitecturesAllowed=$archAllowed",
        $archInstallLine,
        "MinVersion=6.1sp1",
        "PrivilegesRequired=admin",
        "OutputDir=$OutputDir",
        "OutputBaseFilename=$OutputBase",
        "",
        "[Files]",
        "Source: `"$SourceExePath`"; DestDir: `"{app}`"; DestName: `"vehicle_screening.exe`"; Flags: ignoreversion",
        "",
        "[Icons]",
        "Name: `"{autoprograms}\Vehicle Screening`"; Filename: `"{app}\vehicle_screening.exe`"",
        "Name: `"{autodesktop}\Vehicle Screening`"; Filename: `"{app}\vehicle_screening.exe`"; Tasks: desktopicon",
        "",
        "[Tasks]",
        "Name: `"desktopicon`"; Description: `"Create a desktop shortcut`"; GroupDescription: `"Additional icons:`"",
        "",
        "[Run]",
        "Filename: `"{app}\vehicle_screening.exe`"; Description: `"Launch Vehicle Screening`"; Flags: nowait postinstall skipifsilent"
    )

    $lines = @($rawLines | Where-Object { $null -ne $_ })

    [System.IO.File]::WriteAllLines($ScriptPath, $lines, [System.Text.Encoding]::UTF8)
}

$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location -LiteralPath $projectRoot

$buildScript = Join-Path $projectRoot "build_exe.ps1"
Require-File $buildScript "Build script"

$python64 = Resolve-ProjectPath $projectRoot $Python64Exe
$python32 = Resolve-ProjectPath $projectRoot $Python32Exe

$python64SetupHint = @"
Prepare Python 3.8 x64 venv first, for example:
  py -3.8-64 -m venv .venv38
  .\.venv38\Scripts\python.exe -m pip install -U pip
  .\.venv38\Scripts\python.exe -m pip install flask pandas xlrd openpyxl pyinstaller==5.13.2
"@

$python32SetupHint = @"
Prepare Python 3.8 x86 venv first, for example:
  C:\Python38-32\python.exe -m venv .venv38_x86
  .\.venv38_x86\Scripts\python.exe -m pip install -U pip
  .\.venv38_x86\Scripts\python.exe -m pip install flask pandas xlrd openpyxl pyinstaller==5.13.2
Then rerun this script, or pass -Python32Exe explicitly.
"@

Require-File $python64 "Python x64 executable" $python64SetupHint
Require-File $python32 "Python x86 executable" $python32SetupHint

$meta64 = Get-PythonMeta $python64
$meta32 = Get-PythonMeta $python32
Assert-Win7PythonMeta -Meta $meta64 -ArchLabel "x64" -PythonExePath $python64
Assert-Win7PythonMeta -Meta $meta32 -ArchLabel "x86" -PythonExePath $python32

Write-Host "Preflight OK: x64=$($meta64.version)/$($meta64.bits)-bit, x86=$($meta32.version)/$($meta32.bits)-bit" -ForegroundColor Yellow

if (-not $Version) {
    $Version = Get-Date -Format "yyyy.MM.dd.HHmm"
}

$iscc = $null
if (-not $SkipInstaller) {
    $iscc = Resolve-Iscc -PreferredPath $InnoSetupCompiler
    if (-not $iscc) {
        throw @"
Inno Setup compiler (ISCC.exe) was not found.
Install Inno Setup 6, or pass -InnoSetupCompiler explicitly.
Expected default path:
  C:\Program Files (x86)\Inno Setup 6\ISCC.exe

To build Win7 EXE files only, rerun with -SkipInstaller.
"@
    }
    Write-Host "Using ISCC: $iscc" -ForegroundColor Yellow
}

$stamp = Get-Date -Format "yyyyMMdd_HHmmss"
$runRoot = Join-Path $projectRoot "dist\win7_dual\$stamp"
$binDir = Join-Path $runRoot "bin"
$installerDir = Join-Path $runRoot "installer"
$tmpDir = Join-Path $runRoot "_tmp"

New-Item -ItemType Directory -Force -Path $binDir | Out-Null
if (-not $SkipInstaller) {
    New-Item -ItemType Directory -Force -Path $installerDir | Out-Null
    New-Item -ItemType Directory -Force -Path $tmpDir | Out-Null
}

$x64 = Invoke-Win7Build -ProjectRoot $projectRoot -BuildScript $buildScript -ArchLabel "x64" -PythonExePath $python64 -SkipDepsInstallFlag ([bool]$SkipDepsInstall) -OutputDir $binDir
$x86 = Invoke-Win7Build -ProjectRoot $projectRoot -BuildScript $buildScript -ArchLabel "x86" -PythonExePath $python32 -SkipDepsInstallFlag ([bool]$SkipDepsInstall) -OutputDir $binDir

$hashFile = Join-Path $runRoot "SHA256SUMS.txt"
$exeResults = @(
    @{
        Path = $x64.ExePath
        Sha256 = $x64.Sha256
    },
    @{
        Path = $x86.ExePath
        Sha256 = $x86.Sha256
    }
)

if ($SkipInstaller) {
    Write-Sha256Sums -HashFile $hashFile -Items $exeResults

    Write-Host ""
    Write-Host "Done. Win7 EXE files created:" -ForegroundColor Green
    Write-Host "  [x64] $($x64.ExePath)"
    Write-Host "  [x86] $($x86.ExePath)"
    Write-Host "SHA256 list: $hashFile"
    return
}

$installerResults = @()
foreach ($item in @($x64, $x86)) {
    $arch = $item.Arch
    $issPath = Join-Path $tmpDir "vehicle_screening_win7_$arch.iss"
    $outputBase = "vehicle_screening_win7_${arch}_setup"
    New-InnoScript -ScriptPath $issPath -ArchLabel $arch -VersionText $Version -SourceExePath $item.ExePath -OutputDir $installerDir -OutputBase $outputBase

    & $iscc $issPath | Out-Host
    if ($LASTEXITCODE -ne 0) {
        throw "ISCC failed for $arch installer (exit code: $LASTEXITCODE)"
    }

    $setupPath = Join-Path $installerDir "$outputBase.exe"
    Require-File $setupPath "Installer output"
    $setupHash = (Get-FileHash -LiteralPath $setupPath -Algorithm SHA256).Hash.ToLowerInvariant()
    $installerResults += @{
        Arch = $arch
        Path = $setupPath
        Sha256 = $setupHash
    }
}

Write-Sha256Sums -HashFile $hashFile -Items ($exeResults + $installerResults)

# 清理中间 .iss 文件（仅成功路径，失败时保留以便排查）
if (Test-Path -LiteralPath $tmpDir) {
    Remove-Item -LiteralPath $tmpDir -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "Done. Win7 installers created:" -ForegroundColor Green
foreach ($r in $installerResults) {
    Write-Host "  [$($r.Arch)] $($r.Path)"
}
Write-Host "SHA256 list: $hashFile"
