"use strict";

const FILTER_MODE_PAIR = "pair";
const FILTER_MODE_FREQUENT = "frequent";
const FILTER_MODE_KEYPERSON = "keyperson";
const FILTER_MODE_TIMED_CROSS = "timed_cross";
const FILTER_MODE_NIGHT_STAY = "night_stay";
const DEFAULT_NIGHT_STAY_WINDOW_START = "19:00";
const DEFAULT_NIGHT_STAY_WINDOW_END = "05:00";
const DEFAULT_NIGHT_STAY_MIN_MINUTES = 60;
const DEFAULT_NIGHT_STAY_SAME_WINDOW = true;
const DEFAULT_FREQUENT_OCCURRENCE = 2;
const DEFAULT_FREQUENT_START_CLOCK = "00:00";
const DEFAULT_FREQUENT_END_CLOCK = "23:59";
const DEFAULT_PAIR_START_CLOCK = "00:00";
const DEFAULT_PAIR_END_CLOCK = "23:59";
const DEFAULT_KEYPERSON_MIN_OCCURRENCE = 1;
const DEFAULT_KEYPERSON_FREQUENCY_DAYS_PEAK = 25;
const KEYPERSON_FREQUENCY_DAYS_LEFT = 5;
const KEYPERSON_FREQUENCY_DAYS_RIGHT = 31;
const KEYPERSON_FREQUENCY_SCORE_MAX = 60.0;
const KEYPERSON_TIME_SCORE_MAX = 40.0;
const SOURCE_COLUMN_PREFIX = "__source__";
const PAGE_SIZE = 100;
const SESSION_TTL_MS = 2 * 3600 * 1000;
const MAX_UPLOAD_BYTES = 500 * 1024 * 1024;
const MAX_UPLOAD_FILES = 200;

const RISK_LEVEL_META = {
  red: { label: "高风险", style: 4 },
  yellow: { label: "中风险", style: 5 },
  blue: { label: "低风险", style: 6 },
};

const FILTER_MODES = [FILTER_MODE_PAIR, FILTER_MODE_TIMED_CROSS, FILTER_MODE_FREQUENT, FILTER_MODE_KEYPERSON, FILTER_MODE_NIGHT_STAY];

module.exports = {
  FILTER_MODE_PAIR,
  FILTER_MODE_FREQUENT,
  FILTER_MODE_KEYPERSON,
  FILTER_MODE_TIMED_CROSS,
  FILTER_MODE_NIGHT_STAY,
  FILTER_MODES,
  DEFAULT_NIGHT_STAY_WINDOW_START,
  DEFAULT_NIGHT_STAY_WINDOW_END,
  DEFAULT_NIGHT_STAY_MIN_MINUTES,
  DEFAULT_NIGHT_STAY_SAME_WINDOW,
  DEFAULT_FREQUENT_OCCURRENCE,
  DEFAULT_FREQUENT_START_CLOCK,
  DEFAULT_FREQUENT_END_CLOCK,
  DEFAULT_PAIR_START_CLOCK,
  DEFAULT_PAIR_END_CLOCK,
  DEFAULT_KEYPERSON_MIN_OCCURRENCE,
  DEFAULT_KEYPERSON_FREQUENCY_DAYS_PEAK,
  KEYPERSON_FREQUENCY_DAYS_LEFT,
  KEYPERSON_FREQUENCY_DAYS_RIGHT,
  KEYPERSON_FREQUENCY_SCORE_MAX,
  KEYPERSON_TIME_SCORE_MAX,
  SOURCE_COLUMN_PREFIX,
  PAGE_SIZE,
  SESSION_TTL_MS,
  MAX_UPLOAD_BYTES,
  MAX_UPLOAD_FILES,
  RISK_LEVEL_META,
};
